pipeline {
    agent {
        dockerfile { dir 'test-nightly-pipe/docker/ubuntu_16_04_x86_64' }
    }
    stages {
        stage('Build') {
            steps {
                build job: 'build-pipeline', propagate: true, wait: true, parameters:
                    [
                        string(name: 'GITHUB_PR_NUMBER', value: env.GITHUB_PR_NUMBER),
                        booleanParam(name: 'PUBLISH', value: false),
                        booleanParam(name: 'RUN_TESTS', value: false),
                        booleanParam(name: 'RUN_TESTS_MINIMAL', value: true)
                    ]
            }
            post {
                success {
                    setGitHubPullRequestStatus context: 'validate_pr_pipe', state: 'SUCCESS'
                }
                failure {
                    setGitHubPullRequestStatus context: 'validate_pr_pipe', state: 'FAILURE'
                }
            }
        }
    }
}
