pipeline {
    agent {
        node {
            label 'master'
        }
    }
    stages {
        stage('Restore') {
            steps {
              withCredentials([
                  [$class: 'UsernamePasswordMultiBinding', credentialsId: 'SapMachine-github', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASSWORD']
                  ]) {
                sh '''
                  python lib/jenkins_restore.py -t /var/lib/jenkins
                  '''
                }
            }
        }
    }
}
