#!/bin/sh

set -e

jre_tools='${tools}'

case "$$1" in
    configure)
        for i in $$jre_tools; do
            update-alternatives --install /usr/bin/$$i $$i /usr/lib/jvm/sapmachine-${major}-jre/bin/$$i 100
        done
    ;;
esac

exit 0
