pipeline {
    agent {
        dockerfile {
            label 'cloud_foundry'
            dir 'cf-test-pipe/docker'
            additionalBuildArgs '--no-cache'
        }
    }
    stages {
        stage('Test') {
            steps {
                sh '''
                    git clone https://github.com/cloudfoundry/java-buildpack.git
                    cd java-buildpack
                    bundle install
                    bundle exec rake
                '''
            }
        }
    }
    post {
        always {
            cleanWs deleteDirs: true, disableDeferredWipeout: true
        }
    }
}
