pipeline {
    agent {
        dockerfile { dir 'cf-test-pipe/docker' }
    }
    stages {
        stage('Test') {
            steps {
                sh '''
                    git clone https://github.com/cloudfoundry/java-buildpack.git
                    cd java-buildpack
                    bundle install
                    bundle exec rake
                '''
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
