pipeline {
    agent {
        node {
            label 'master'
        }
    }
    stages {
        stage('Backup') {
            steps {
              withCredentials([
                  [$class: 'UsernamePasswordMultiBinding', credentialsId: 'SapMachine-github', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASSWORD']
                  ]) {
                sh '''
                  python lib/jenkins_backup.py -s /var/lib/jenkins
                  '''
                }
            }
        }
    }
}
