pipeline {

    stages {
        stage('Run Minimal Tests') {
            steps {
            build job: 'test-pipeline-jtreg-hotspot', propagate: true, wait: true, parameters:
                [
                    string(name: 'GIT_TAG_NAME', value: GIT_TAG_NAME),
                    string(name: 'test_suite', value: 'hotspot'),
                    string(name: 'test_groups', value: ':hotspot_tier1')
                ]
            }
        }
    }
}
