pipeline {
    agent {
        node {
            label 'agent-alpine-local'
        }
    }
    stages {
        stage('Build') {
            environment {
              GITHUB_API_ACCESS_TOKEN = credentials('SapMachine-Github-Token')
            }
            steps {
                sh 'rm -f *.apk'
                sh "python lib/make_apk.py --tag=${params.GIT_TAG_NAME} --templates-directory=apk-pipe/templates"
            }
            post {
                success {
                    archive "*.apk"
                }
            }
        }
        stage('Deploy') {
            when {
                expression { params.DEPLOY == true }
            }
            steps {
                sh "cp *.apk ${params.DEPLOY_FOLDER}"
                sh "python lib/recreate_apk_repository.py -r ${params.DEPLOY_FOLDER} -k ${params.KEY_DIR}/sapmachine@sap.com-5a673212.rsa"
            }
        }
    }
    post {
        always {
            cleanWs deleteDirs: true, disableDeferredWipeout: true
        }
    }
}