#!/bin/sh

set -e

vm_tools='${tools}'

case "$$1" in
    configure)
        for i in $$vm_tools; do
            update-alternatives --install /usr/bin/$$i $$i /usr/lib/jvm/sapmachine-${major}/bin/$$i 100
        done
    ;;
esac

exit 0
