pipeline {
    agent {
        dockerfile { dir 'debian-pipe/docker/ubuntu_16_04_x86_64' }
    }
    stages {
        stage('Build') {
            steps {
                sh "python lib/make_deb.py --tag=${params.tag} --templates-directory=debian-pipe/templates"
            }
            post {
                success {
                    archive '*.deb'
                }
            }
        }
        stage('Deploy') {
            sshagent (credentials: ['jenkins_ssh_key']) {
                sh 'scp *.deb jenkins@sapmachine-ubuntu.sapcloud.io:deb/amd64'
            }
        }
    }
}