pipeline {
    agent {
        dockerfile { dir 'debian-pipe/docker/ubuntu_16_04_x86_64' }
    }
    stages {
        stage('Build') {
            steps {
                sh 'rm -f *.deb'
                sh "python lib/make_deb.py --tag=${params.tag} --templates-directory=debian-pipe/templates"
            }
            post {
                success {
                    archive "*.deb"
                }
            }
        }
        stage('Deploy') {
            when {
                expression { params.deploy == true }
            }
            steps {
                sshagent (credentials: ['jenkins_ssh_key']) {
                    sh "mkdir /home/jenkins/.ssh"
                    sh "chmod 700 /home/jenkins/.ssh"
                    sh "ssh-keyscan -t rsa ${params.deploy_host} > /home/jenkins/.ssh/known_hosts"
                    sh "scp *.deb jenkins@${params.deploy_host}:${params.deploy_folder}"
                    sh "scp lib/utils.py lib/recreate_deb_repository.py jenkins@${params.deploy_host}:"
                    sh "ssh jenkins@${params.deploy_host} python recreate_deb_repository.py -r ${params.deploy_folder}"
                }
            }
        }
    }
}