
pipeline {
     agent {
        dockerfile { dir 'git-hg' }
      }
      stages {
        stage('Build') {
            steps {
              withCredentials([
                    [$class: 'UsernamePasswordMultiBinding', credentialsId: 'SapMachine-github', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASSWORD']
                    ]) {
                    sh '$PWD/git-hg/update_repo.sh'
                }
            }
        }
    }
}
