FROM ubuntu:16.04

RUN apt-get update && apt-get install -qq -y --no-install-recommends \
zip \
wget \
git \
unzip \
realpath \
ca-certificates \
curl \
python \
mercurial \
openjdk-8-jdk \
ant \
make
