pipeline {
    agent {
        node {
            label 'agent-ubuntu-local'
        }
    }
    stages {
        stage('Copy Artifacts') {
            steps {
                script {
                    step ([$class: 'CopyArtifact',
                    selector: buildParameter("${BUILD_SELECTOR}"),
                    projectName: JDK_BUILD_JOB,
                    filter: "apidocs.zip",
                    target: env.WORKSPACE]);
                }
            }
        }
        stage('Extract Archive') {
            steps {
                script {
                    def match = JOB_NAME =~ /\S*-([0-9]+)-\S*/
                    env.MAJOR_VERSION = match[0][1]
                }

                sh "cd /var/docs/api/${env.MAJOR_VERSION} && rm -rf *"
                sh "cd /var/docs/api/${env.MAJOR_VERSION} && unzip ${env.WORKSPACE}/apidocs.zip"
            }
        }
    }
}
