pipeline {
    agent {
        dockerfile {
            label linux_x86_64
            dir 'dockerfiles/ubuntu_14_04_x86_64'
        }
    }
    stages {
        stage('Generate') {
            environment {
              GITHUB_API_ACCESS_TOKEN = credentials('SapMachine-Github-Token')
            }
            steps {
                withCredentials([
                  [$class: 'UsernamePasswordMultiBinding', credentialsId: 'SapMachine-github', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASSWORD']
                  ]) {
                    sh "python lib/generate_website_data.py"
                  }
            }
        }
    }
    post {
        always {
            cleanWs deleteDirs: true, disableDeferredWipeout: true
        }
    }
}
