pipeline {
    agent {
        dockerfile { dir 'debian-pipe/docker/ubuntu_16_04_x86_64' }
    }
    stages {
        stage('Build') {
            environment {
              GITHUB_API_ACCESS_TOKEN = credentials('SapMachine-Github-Token')
            }
            steps {
                sh "python lib/generate_website_data.py"
            }
        }
    post {
        always {
            cleanWs()
        }
    }
}
