FROM alpine:3.5

MAINTAINER Sapmachine <sapmachine@sap.com>

RUN apk update; \
    apk add bash; \
    apk add file; \
    apk add grep; \
    apk add zip; \
    apk add tar; \
    apk add shadow; \
    apk add alpine-sdk;
