FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -qq -y --no-install-recommends \
autoconf \
bzip2 \
ca-certificates \
cpio \
gcc \
git \
g++ \
make \
rpm2cpio \
texinfo \
wget \
xz-utils
