#!/bin/sh

set -e

jre_tools='${tools}'

case "$$1" in
    configure)
        for i in $$jre_tools; do
            update-alternatives --install /usr/bin/$$i $$i /opt/sapmachine-10-jre/bin/$$i 100
        done
    ;;
esac

exit 0