pipeline {
    agent any
    stages {
        stage('Merge') {
            environment {
              SAPMACHINE_GIT_REPO = 'github.com/SAP/SapMachine.git'
              SAPMACHINE_GIT_BRANCH = 'sapmachine'
              SAPMACHINE_ARCHIVE_NAME_PREFIX = 'sapmachine_linux-x64'
              SAPMACHINE_PUBLISH_GITHUB_TOKEN = credentials('SapMachine-Github-Token')
              SAPMACHINE_PUBLISH_GITHUB_REPO_NAME = 'SapMachine'
              SAPMACHINE_PUBLISH_GITHUB_USER = 'SAP'
            }
            steps {
              withCredentials([
                  [$class: 'UsernamePasswordMultiBinding', credentialsId: 'SapMachine-github', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASSWORD']
                  ]) {
                sh '''
                  check-tags/check_tag_and_create_pr.sh .result
                  '''
                }
            }
        }

    stage('Read Result') {
      steps {
        script {
          test_branch = readFile '.result'
        }
      }
    }
    stage('trigger build') {
      when {
        expression {
          return test_branch != '';
           }
         }
      steps {
        build job: 'build-pipeline', propagate: true, wait: true, parameters:
          [
              string(name: 'GIT_TAG_NAME', value: test_branch),
              booleanParam(name: 'PUBLISH', value: true),
              booleanParam(name: 'RUN_TESTS', value: true)
            ]
          ]
        }
      }
    }
  }
