pipeline {
    agent {
        dockerfile {
            dir "dockerfiles/ubuntu_16_04_x86_64"
            reuseNode true
            label "linux_x86_64"
        }
    }
    stages {
        stage('Merge') {
            environment {
                SAPMACHINE_GIT_REPO = 'github.com/SAP/SapMachine.git'
                SAPMACHINE_GIT_BRANCH = 'sapmachine'
                SAPMACHINE_ARCHIVE_NAME_PREFIX = 'sapmachine_linux-x64'
                SAPMACHINE_PUBLISH_GITHUB_TOKEN = credentials('SapMachine-Github-Token')
                SAPMACHINE_PUBLISH_GITHUB_REPO_NAME = 'SapMachine'
                SAPMACHINE_PUBLISH_GITHUB_USER = 'SAP'
                JENKINS_CREDENTIALS = credentials('sapmachine-jenkins')
                GITHUB_API_ACCESS_TOKEN = credentials('SapMachine-Github-Token')
            }
            steps {
              withCredentials([
                    [$class: 'UsernamePasswordMultiBinding', credentialsId: 'SapMachine-github', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASSWORD']
                    ]) {
                    sh '''
                    python lib/merge_jdk_tags.py
                    python lib/create_sapmachine_tags.py
                    '''
                }
            }
        }
    }
}
