pipeline {
    agent {
        label params.AGENT_LABEL
    }
    stages {
        stage('Build') {
            agent {
                dockerfile {
                    label params.AGENT_LABEL
                    dir params.DOCKER_DIR
                }
            }
            steps {
                script {
                    def match = params.TAG =~ /jtreg([0-9]+\.[0-9]+)-(b[0-9]*).*/
                    env.BUILD_NUMBER = match[0][2]
                    env.BUILD_VERSION = match[0][1]
                }
                sh "rm -rf ${env.WORKSPACE}/jtreg"
                sh "hg clone http://hg.openjdk.java.net/code-tools/jtreg ${env.WORKSPACE}/jtreg"
                sh "cd ${env.WORKSPACE}/jtreg && hg up ${params.TAG}"
                sh "cd ${env.WORKSPACE}/jtreg && bash make/build-all.sh /usr/lib/jvm/java-8-openjdk-*"
                sh "cp ${env.WORKSPACE}/jtreg/build/images/jtreg.zip ${env.WORKSPACE}/jtreg.zip"
            }
            post {
                success {
                    archive 'jtreg.zip'
                }
            }
        }
    }
    post {
        always {
            cleanWs deleteDirs: true, disableDeferredWipeout: true
        }
    }
}
