pipeline {
    agent {
        label params.AGENT_LABEL
    }
    stages {
        stage('Build') {
            agent {
                dockerfile {
                    label params.AGENT_LABEL
                    dir params.DOCKER_DIR
                    reuseNode true
                }
            }
            environment {
              SAPMACHINE_PUBLISH_GITHUB_TOKEN = credentials('SapMachine-Github-Token')
              SAPMACHINE_PUBLISH_GITHUB_REPO_NAME = 'SapMachine'
              SAPMACHINE_PUBLISH_GITHUB_USER = 'SAP'
            }
            steps {
              withCredentials([
                  [$class: 'UsernamePasswordMultiBinding', credentialsId: 'SapMachine-github', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASSWORD']
                  ]) {
                sh '''
                  build-pipe/build.sh
                  '''
                }
            }
            post {
                success {
                    junit 'gtest.xml'
                }
            }
        }
        stage('Archive') {
            agent {
                dockerfile {
                    label params.AGENT_LABEL
                    dir params.DOCKER_DIR
                    reuseNode true
                }
            }
            steps {
                archive 'build.tar.gz'
                archive 'test.zip'
                archive 'apidocs.zip'

                script {
                    def jdk_bundle_name = readFile "${env.WORKSPACE}/jdk_bundle_name.txt"
                    def jre_bundle_name = readFile "${env.WORKSPACE}/jre_bundle_name.txt"

                    step ([$class: 'ArtifactArchiver', artifacts: jdk_bundle_name]);
                    step ([$class: 'ArtifactArchiver', artifacts: jre_bundle_name]);
                }
            }
        }
        stage('Run Tests') {
            agent {
                dockerfile {
                    label params.AGENT_LABEL
                    dir params.DOCKER_DIR
                    reuseNode true
                }
            }
            when {
                expression { params.RUN_TESTS == true}
            }
            steps {
                script {
                    def sapmachine_git_repository = 'https://github.com/SAP/SapMachine.git'
                    def sapmachine_git_branch = 'sapmachine'

                    if (params.SAPMACHINE_GIT_REPOSITORY) {
                        sapmachine_git_repository = params.SAPMACHINE_GIT_REPOSITORY
                    }

                    if (params.SAPMACHINE_GIT_BRANCH) {
                        sapmachine_git_branch = params.SAPMACHINE_GIT_BRANCH
                    }

                    build job: HOTSPOT_TEST_JOB, propagate: params.PROPAGATE_RESULT, wait: true, parameters:
                            [
                                string(name: 'SAPMACHINE_GIT_REPOSITORY', value: sapmachine_git_repository),
                                string(name: 'SAPMACHINE_GIT_BRANCH', value: sapmachine_git_branch),
                                string(name: 'GITHUB_PR_NUMBER', value: params.GITHUB_PR_NUMBER),
                                string(name: 'GIT_TAG_NAME', value: params.GIT_TAG_NAME)
                            ]

                    build job: JDK_TEST_JOB, propagate: params.PROPAGATE_RESULT, wait: true, parameters:
                            [
                                string(name: 'SAPMACHINE_GIT_REPOSITORY', value: sapmachine_git_repository),
                                string(name: 'SAPMACHINE_GIT_BRANCH', value: sapmachine_git_branch),
                                string(name: 'GITHUB_PR_NUMBER', value: params.GITHUB_PR_NUMBER),
                                string(name: 'GIT_TAG_NAME', value: params.GIT_TAG_NAME)
                            ]

                    build job: LANGTOOLS_TEST_JOB, propagate: params.PROPAGATE_RESULT, wait: true, parameters:
                            [
                                string(name: 'SAPMACHINE_GIT_REPOSITORY', value: sapmachine_git_repository),
                                string(name: 'SAPMACHINE_GIT_BRANCH', value: sapmachine_git_branch),
                                string(name: 'GITHUB_PR_NUMBER', value: params.GITHUB_PR_NUMBER),
                                string(name: 'GIT_TAG_NAME', value: params.GIT_TAG_NAME)
                            ]

                }
            }
        }
        stage('Publish GitHub') {
            agent {
                dockerfile {
                    label params.AGENT_LABEL
                    dir params.DOCKER_DIR
                    reuseNode true
                }
            }
            when {
                expression { params.PUBLISH == true }
            }
            environment {
              SAPMACHINE_GIT_REPO = 'github.com/SAP/SapMachine.git'
              SAPMACHINE_PUBLISH_GITHUB_TOKEN = credentials('SapMachine-Github-Token')
              SAPMACHINE_PUBLISH_GITHUB_REPO_NAME = 'SapMachine'
              SAPMACHINE_PUBLISH_GITHUB_USER = 'SAP'
            }
            steps {
                sh '''
                build-pipe/publish.sh
                '''
            }
        }
        stage('Publish Website Data') {
            agent {
                dockerfile {
                    label params.AGENT_LABEL
                    dir params.DOCKER_DIR
                    reuseNode true
                }
            }
            when {
                expression { params.PUBLISH == true }
            }
            steps {
                build job: 'generate-website-data', propagate: false, wait: false
            }
        }
        stage('Publish CF Java Buildpack Data') {
            agent {
                dockerfile {
                    label params.AGENT_LABEL
                    dir params.DOCKER_DIR
                    reuseNode true
                }
            }
            when {
                expression { params.PUBLISH == true && params.AGENT_LABEL == "linux_x86_64" }
            }
            steps {
                script {
                    def match = params.GIT_TAG_NAME =~ /[^-]*-([0-9]+)[\.0-9]*\+.*/
                    env.MAJOR_VERSION = match[0][1]
                }
                build job: 'generate-cf-data', propagate: false, wait: false, parameters:
                    [
                        string(name: 'MAJOR', value: env.MAJOR_VERSION)
                    ]
            }
        }
        stage('Publish Debian Linux Packages') {
            agent {
                dockerfile {
                    label params.AGENT_LABEL
                    dir params.DOCKER_DIR
                    reuseNode true
                }
            }
            when {
                expression { JOB_NAME ==~ /((\S*)(release)$)/  && params.PUBLISH == true }
            }
            steps {
            build job: 'debian-pipeline', propagate: false, wait: true, parameters:
                [
                    string(name: 'GIT_TAG_NAME', value: params.GIT_TAG_NAME),
                    [$class: 'BooleanParameterValue', name: 'DEPLOY', value: true]
                ]
            }
        }
        stage('Publish Alpine Linux Packages') {
            agent {
                dockerfile {
                    label params.AGENT_LABEL
                    dir params.DOCKER_DIR
                    reuseNode true
                }
            }
            when {
                expression { JOB_NAME ==~ /((\S*)(release-alpine)$)/  && params.PUBLISH == true && params.AGENT_LABEL == "linux_x86_64"}
            }
            steps {
            build job: 'apk-pipeline', propagate: false, wait: true, parameters:
                [
                    string(name: 'GIT_TAG_NAME', value: params.GIT_TAG_NAME),
                    [$class: 'BooleanParameterValue', name: 'DEPLOY', value: true]
                ]
            }
        }
        stage('Publish Docker Images') {
            agent {
                dockerfile {
                    label params.AGENT_LABEL
                    dir params.DOCKER_DIR
                    reuseNode true
                }
            }
            when {
                expression { JOB_NAME ==~ /((\S*)(release)(\S*))/ && params.PUBLISH == true && params.AGENT_LABEL == "linux_x86_64" }
            }
            steps {
            build job: DOCKER_BUILD_JOB, propagate: false, wait: true, parameters:
                [
                    string(name: 'GIT_TAG_NAME', value: params.GIT_TAG_NAME),
                    [$class: 'BooleanParameterValue', name: 'PUBLISH', value: true],
                    [$class: 'BooleanParameterValue', name: 'RUN_TESTS', value: true]
                ]
            }
        }
    }
    post {
        always {
            cleanWs deleteDirs: true, disableDeferredWipeout: true
        }
    }
}
