pipeline {
    agent {
        dockerfile {
            label 'repository'
            dir 'dockerfiles/infrastructure'
            reuseNode true
        }
    }
    stages {
        stage('Generate') {
            steps {
                withCredentials([
                        [$class: 'UsernamePasswordMultiBinding', credentialsId: 'sapmachine-jenkins', usernameVariable: 'JENKINS_USER', passwordVariable: 'JENKINS_PASSWORD']
                        ]) {
                    sh "cd jenkins-job-generator && jenkins-jobs --conf jenkins_jobs.ini --user ${JENKINS_USER} --password ${JENKINS_PASSWORD} update --delete-old ./definitions"
                }
            }
        }
    }
}