pipeline {
    agent {
        dockerfile {
            label params.AGENT_LABEL
            dir params.DOCKER_DIR
            reuseNode true
        }
    }
    stages {
        stage('Generate') {
            steps {
                withCredentials([
                        [$class: 'UsernamePasswordMultiBinding', credentialsId: 'sapmachine-jenkins', usernameVariable: 'JENKINS_USER', passwordVariable: 'JENKINS_PASSWORD']
                        ]) {
                    sh "cd jenkins-job-generator && jenkins-jobs --conf jenkins_jobs.ini --user ${JENKINS_USER} --password ${JENKINS_PASSWORD} ${params.ACTION} ${params.ACTION_ARGS} ${params.TEMPLATE_OR_JOB}"
                }
            }
        }
    }
}