name: Triggered workflow from wdf

on:
    workflow_dispatch:
        inputs:
            event_type:
                description: 'Event type'
                required: false
                default: 'gh-page-build-on-infra'
    push:
        branches: [ "github_triggers_workflow"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Triggered from Enterprise instance!"
