name: Triggered workflow from wdf

on:
    repository_dispatch:
        types: [gh-page-build-on-infra]
    workflow_dispatch:
    push:
        branches: [ "github_triggers_workflow"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Triggered from Enterprise instance!"
