# used for creating the new Feature Release Build in March and September.
# CPU updates in January/April/July/October are done via publish-gardenlinux-images.yml
name: Build and Publish ONCE SapMachine new Feature Releases container images to the SAP GitHub Container Registry
on:
  workflow_dispatch:

jobs:
  publish_images:
    strategy:
        matrix:
          sapMachineVersion: [25]
          gardenLinuxVersion: [1592]
    uses: ./.github/workflows/publish-container-images.yml
    with:
      sapMachineVersion: ${{ matrix.sapMachineVersion }}
      gardenLinuxVersion:  ${{ matrix.gardenLinuxVersion }}
