name: Pull and Republish SapMachine Images without -1877 Suffix

on:
  workflow_dispatch:

jobs:
  republish_images:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Authenticate with GitHub Container Registry
        run: |
          podman login -u token -p ${{ github.token }} ghcr.io

      - name: Pull and Republish SapMachine images for 17-jdk-gl-1877
        run: |
          SM_REGISTRY="ghcr.io/sap/sapmachine"
          old_tag=17-jdk-gl-1877
          new_tag=17-jdk
          podman tag ${SM_REGISTRY}:$old_tag ${SM_REGISTRY}:$new_tag
          podman push ${SM_REGISTRY}:$new_tag

      - name: Pull and Republish SapMachine images for 17-jdk-headless-gl-1877
        run: |
          SM_REGISTRY="ghcr.io/sap/sapmachine"
          old_tag=17-jdk-headless-gl-1877
          new_tag=17-jdk-headless
          podman tag ${SM_REGISTRY}:$old_tag ${SM_REGISTRY}:$new_tag
          podman push ${SM_REGISTRY}:$new_tag

      - name: Pull and Republish SapMachine images for 17-jre-gl-1877
        run: |
          SM_REGISTRY="ghcr.io/sap/sapmachine"
          old_tag=17-jre-gl-1877
          new_tag=17-jre
          podman tag ${SM_REGISTRY}:$old_tag ${SM_REGISTRY}:$new_tag
          podman push ${SM_REGISTRY}:$new_tag

      - name: Pull and Republish SapMachine images for 17-jre-headless-gl-1877
        run: |
          SM_REGISTRY="ghcr.io/sap/sapmachine"
          old_tag=17-jre-headless-gl-1877
          new_tag=17-jre-headless
          podman tag ${SM_REGISTRY}:$old_tag ${SM_REGISTRY}:$new_tag
          podman push ${SM_REGISTRY}:$new_tag

      - name: Pull and Republish SapMachine images for 21-jdk-gl-1877
        run: |
          SM_REGISTRY="ghcr.io/sap/sapmachine"
          old_tag=21-jdk-gl-1877
          new_tag=21-jdk
          podman tag ${SM_REGISTRY}:$old_tag ${SM_REGISTRY}:$new_tag
          podman push ${SM_REGISTRY}:$new_tag

      - name: Pull and Republish SapMachine images for 21-jdk-headless-gl-1877
        run: |
          SM_REGISTRY="ghcr.io/sap/sapmachine"
          old_tag=21-jdk-headless-gl-1877
          new_tag=21-jdk-headless
          podman tag ${SM_REGISTRY}:$old_tag ${SM_REGISTRY}:$new_tag
          podman push ${SM_REGISTRY}:$new_tag

      - name: Pull and Republish SapMachine images for 21-jre-gl-1877
        run: |
          SM_REGISTRY="ghcr.io/sap/sapmachine"
          old_tag=21-jre-gl-1877
          new_tag=21-jre
          podman tag ${SM_REGISTRY}:$old_tag ${SM_REGISTRY}:$new_tag
          podman push ${SM_REGISTRY}:$new_tag

      - name: Pull and Republish SapMachine images for 21-jre-headless-gl-1877
        run: |
          SM_REGISTRY="ghcr.io/sap/sapmachine"
          old_tag=21-jre-headless-gl-1877
          new_tag=21-jre-headless
          podman tag ${SM_REGISTRY}:$old_tag ${SM_REGISTRY}:$new_tag
          podman push ${SM_REGISTRY}:$new_tag

      - name: Pull and Republish SapMachine images for 25-jdk-gl-1877
        run: |
          SM_REGISTRY="ghcr.io/sap/sapmachine"
          old_tag=25-jdk-gl-1877
          new_tag=25-jdk
          podman tag ${SM_REGISTRY}:$old_tag ${SM_REGISTRY}:$new_tag
          podman push ${SM_REGISTRY}:$new_tag

      - name: Pull and Republish SapMachine images for 25-jdk-headless-gl-1877
        run: |
          SM_REGISTRY="ghcr.io/sap/sapmachine"
          old_tag=25-jdk-headless-gl-1877
          new_tag=25-jdk-headless
          podman tag ${SM_REGISTRY}:$old_tag ${SM_REGISTRY}:$new_tag
          podman push ${SM_REGISTRY}:$new_tag

      - name: Pull and Republish SapMachine images for 25-jre-gl-1877
        run: |
          SM_REGISTRY="ghcr.io/sap/sapmachine"
          old_tag=25-jre-gl-1877
          new_tag=25-jre
          podman tag ${SM_REGISTRY}:$old_tag ${SM_REGISTRY}:$new_tag
          podman push ${SM_REGISTRY}:$new_tag

      - name: Pull and Republish SapMachine images for 25-jre-headless-gl-1877
        run: |
          SM_REGISTRY="ghcr.io/sap/sapmachine"
          old_tag=25-jre-headless-gl-1877
          new_tag=25-jre-headless
          podman tag ${SM_REGISTRY}:$old_tag ${SM_REGISTRY}:$new_tag
          podman push ${SM_REGISTRY}:$new_tag
