name: Build and Publish ONCE SapMachine new Feature Releases container images to the SAP GitHub Container Registry

on:
  workflow_dispatch:

jobs:
  publish_images:
    strategy:
      matrix:
        sapMachineVersion: [17, 21, 25]
        gardenLinuxVersion: [1877]
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install qemu dependency for multi-arch build
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Publish SapMachine images
        run: |
          SM_FLAVOURS=(jdk jdk-headless jre jre-headless)
          SM_REGISTRY="ghcr.io/sap/sapmachine"
          cd dockerfiles/${{ matrix.sapMachineVersion }}/gardenlinux/${{ matrix.gardenLinuxVersion }}
          podman login -u token -p ${{ github.token }} ghcr.io

          for sm_flvr in "${SM_FLAVOURS[@]}" ; do
            tag=${{ matrix.sapMachineVersion }}-${sm_flvr}-gl-${{ matrix.gardenLinuxVersion }}
            short_tag=${{ matrix.sapMachineVersion }}-${sm_flvr}
            cd ${sm_flvr}
            podman manifest create ${SM_REGISTRY}:$tag
            podman build --platform linux/amd64,linux/arm64 --manifest ${SM_REGISTRY}:$tag .
            podman manifest push ${SM_REGISTRY}:$tag

            # Tag the image with the short tag
            podman tag ${SM_REGISTRY}:$tag ${SM_REGISTRY}:$short_tag
            podman manifest create --replace ${SM_REGISTRY}:$short_tag
            podman manifest push ${SM_REGISTRY}:$short_tag

            cd ..
          done
